# Generated by Django 3.2.8 on 2021-11-09 19:26

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('runid', models.AutoField(primary_key=True, serialize=False)),
                ('inputFile', models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/Users/boorish/Documents/programowanie/engineer/code/cross-validation-web-app/backend/server/media'), upload_to='uploads')),
                ('paramList', models.TextField(default=None)),
                ('targetColumn', models.CharField(default=None, max_length=64)),
                ('adjust', models.FloatField(blank=True, default=None, null=True)),
                ('round', models.IntegerField(default=5)),
                ('fixed', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('threshold', models.IntegerField(blank=True, default=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsOLS',
            fields=[
                ('resultolsid', models.AutoField(primary_key=True, serialize=False)),
                ('outliers', models.CharField(default=None, max_length=255)),
                ('mean_abs_percentage_error', models.FloatField(default=None)),
                ('percentage_error_vect', models.TextField(default=None)),
                ('mean_percentage_error', models.FloatField(default=None)),
                ('median_percentage_error', models.FloatField(default=None)),
                ('rmsre', models.FloatField(default=None)),
                ('stddev_abs_percentage_error', models.FloatField(default=None)),
                ('stddev_relative_error', models.FloatField(default=None)),
                ('rmse', models.CharField(default=None, max_length=64)),
                ('r2_score', models.CharField(default=None, max_length=64)),
                ('runid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultsols', to='MyAPI.parameters')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsNNLS',
            fields=[
                ('resultnnlsid', models.AutoField(primary_key=True, serialize=False)),
                ('outliers', models.CharField(default=None, max_length=255)),
                ('mean_abs_percentage_error', models.FloatField(default=None)),
                ('percentage_error_vect', models.TextField(default=None)),
                ('mean_percentage_error', models.FloatField(default=None)),
                ('median_percentage_error', models.FloatField(default=None)),
                ('rmsre', models.FloatField(default=None)),
                ('stddev_abs_percentage_error', models.FloatField(default=None)),
                ('stddev_relative_error', models.FloatField(default=None)),
                ('rmse', models.CharField(default=None, max_length=64)),
                ('r2_score', models.CharField(default=None, max_length=64)),
                ('runid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultsnnls', to='MyAPI.parameters')),
            ],
        ),
    ]
