# Generated by Django 3.2.8 on 2021-10-28 18:40

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputFile', models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/Users/boorish/Documents/programowanie/engineer/code/cross-validation-web-app/backend/server/media'), upload_to='uploads')),
                ('paramList', models.TextField(blank=True, default=None, null=True)),
                ('targetColumn', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('adjust', models.FloatField(blank=True, default=None, null=True)),
                ('round', models.IntegerField(default=5)),
                ('fixed', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('threshold', models.IntegerField(blank=True, default=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsOLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outliers', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('mean_abs_percentage_error', models.FloatField(blank=True, default=None, null=True)),
                ('percentage_error_vect', models.TextField(blank=True, default=None, null=True)),
                ('mean_percentage_error', models.FloatField(blank=True, default=None, null=True)),
                ('median_percentage_error', models.FloatField(blank=True, default=None, null=True)),
                ('rmsre', models.FloatField(blank=True, default=None, null=True)),
                ('stddev_abs_percentage_error', models.FloatField(blank=True, default=None, null=True)),
                ('stddev_relative_error', models.FloatField(blank=True, default=None, null=True)),
                ('rmse', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('r2_score', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('inputData', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyAPI.parameters')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsNNLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outliers', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('mean_abs_percentage_error', models.FloatField(blank=True, default=None, null=True)),
                ('percentage_error_vect', models.TextField(blank=True, default=None, null=True)),
                ('mean_percentage_error', models.FloatField(blank=True, default=None, null=True)),
                ('median_percentage_error', models.FloatField(blank=True, default=None, null=True)),
                ('rmsre', models.FloatField(blank=True, default=None, null=True)),
                ('stddev_abs_percentage_error', models.FloatField(blank=True, default=None, null=True)),
                ('stddev_relative_error', models.FloatField(blank=True, default=None, null=True)),
                ('rmse', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('r2_score', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('inputData', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyAPI.parameters')),
            ],
        ),
    ]
