# Generated by Django 3.2.8 on 2021-10-20 17:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='adjust',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='parameters',
            name='fixed',
            field=models.CharField(default='Value to fix', max_length=32),
        ),
        migrations.AddField(
            model_name='parameters',
            name='inputFile',
            field=models.FileField(default='settings.MEDIA_ROOT/uploads/example.csv', storage=django.core.files.storage.FileSystemStorage(location='/Users/boorish/Documents/programowanie/engineer/code/cross-validation-web-app/backend/server/media'), upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='paramList',
            field=models.TextField(default='list of parameters', max_length=256),
        ),
        migrations.AddField(
            model_name='parameters',
            name='round',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='parameters',
            name='targetColumn',
            field=models.CharField(default='name of target column', max_length=32),
        ),
    ]
