# Generated by Django 3.2.8 on 2021-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_alter_results_runid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='r2_score_nnls',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='results',
            name='r2_score_ols',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='results',
            name='rmse_nnls',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='results',
            name='rmse_ols',
            field=models.FloatField(default=None),
        ),
    ]
