# Generated by Django 3.2.8 on 2021-10-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_auto_20211020_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='fixed',
            field=models.CharField(blank=True, default='Value to fix', max_length=32),
        ),
    ]
