# Generated by Django 3.2.8 on 2021-10-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0003_alter_parameters_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
    ]
