# Generated by Django 3.2.8 on 2021-10-21 18:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0004_parameters_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputFile', models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='/Users/boorish/Documents/programowanie/engineer/code/cross-validation-web-app/backend/server/media'), upload_to='uploads')),
                ('paramList', models.TextField(default='', max_length=256)),
                ('targetColumn', models.CharField(default='', max_length=32)),
                ('adjust', models.FloatField(default=5.0)),
                ('round', models.IntegerField(default=5)),
                ('fixed', models.CharField(blank=True, default='', max_length=32)),
                ('threshold', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='parameters',
        ),
    ]
